export source_db_user=""
export source_db_password=""
export source_db_server_name=""
export source_db_database_name=""
export target_db_user=""
export target_db_password=""
export target_db_server_name=""
export target_db_database_name=""